# -*- coding: utf-8 -*-
"""eyeapp.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqdUtTaS0YYw5bV7-psnWdcsXS2twzYt
"""


import streamlit as st
from datetime import datetime

# Dummy backend imports (replace with actual later)
# from backend import save_image, get_embeddings, match_embeddings
# from database import register_student, mark_attendance

st.set_page_config(page_title="AI Attendance System", layout="centered")

st.title("📸 Eye-Based Attendance System")

# --- Tabs ---
tab1, tab2 = st.tabs(["📝 Register Student", "✅ Mark Attendance"])

# --- Tab 1: Register Student ---
with tab1:
    st.subheader("Register a New Student")

    with st.form("registration_form"):
        name = st.text_input("Full Name")
        roll_no = st.text_input("Roll Number")
        department = st.text_input("Department")
        image_file = st.file_uploader("Upload Face Image", type=["jpg", "jpeg", "png"])

        submit_btn = st.form_submit_button("Register")

    if submit_btn:
        if not name or not roll_no or not department or not image_file:
            st.error("Please fill all fields and upload an image.")
        else:
            # Save image to folder
            # embedding = get_embeddings(image_file)
            # save_image(image_file, roll_no)
            # register_student(name, roll_no, department, "path_to_image", "path_to_embedding")

            st.success(f"✅ Student '{name}' registered successfully!")
            st.balloons()

# --- Tab 2: Mark Attendance ---
with tab2:
    st.subheader("Upload Photo to Mark Attendance")

    image_to_check = st.file_uploader("Upload Group/Single Image", type=["jpg", "jpeg", "png"], key="attendance_image")

    if image_to_check:
        # faces = detect_faces(image_to_check)
        # matches = match_embeddings(faces)
        # if matches:
        #     mark_attendance(student_id, date, time, confidence)
        #     st.success("✅ Student marked present")
        # else:
        #     st.error("❌ Face not recognized")

        st.info("⚙️ Attendance marking logic will run here (connect backend)")
        st.success("✅ Example: 'Student marked present!'")

